### ISSUE TITLE
Error with `deployment get -o wide` in bedrock CLI

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1280]
**Describe the bug:**
From docs:
>   -o, --output <output-format>         Output the information one of the following: normal, wide, JSON (default: "normal")

When I run: 
```shell
$ ./spk-macos deployment get -o wide
error:   Error occurred while getting deployment(s)
error:   TypeError: Cannot read property 'replace' of undefined
(node:20241) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at eval (webpack:///./node_modules/spektate/lib/repository/IAzureDevOpsRepo.js?:38:52)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:20241) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

Error log from `spk.log`
```shell
017Z","stack":"Error: TypeError: Cannot read property 'replace' of undefined\n    at eval (webpack:///./src/commands/deployment/get.ts?:127:20)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"}
error: Error occurred while getting deployment(s) {"service":"spk","timestamp":"2020-03-30T19:13:24.610Z"}
error: TypeError: Cannot read property 'replace' of undefined {"service":"spk","timestamp":"2020-03-30T19:13:24.613Z","stack":"Error: TypeError: Cannot read property 'replace' of undefined\n    at eval (webpack:///./src/commands/deployment/get.ts?:127:20)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"}
```

When I remove the `-o wide` I get
```
$ ./spk-macos deployment get
Start Time             Service         Deployment   Commit  Src to ACR Image Tag                                         Result ACR to HLD Env    Hld Commit Result HLD to Manifest Result
3/30/2020, 11:50:01 AM quick-start-app d2b67d3a1ecb cd55d78 1646       quick-start-app-quick-start-app:master-20200330.1 ✓      1646       MASTER b158e69    ✓      1647            ✓     
3/30/2020, 11:49:12 AM -               bd61c68f8d59 -       -          -                                                        -          -      f1b94ad           1645            ✓     
```

When I include ` -o json` I get json output.

This is using master branch version of the bedrock cli

**Comment by samiyaakhtar** [comment]
This was caused due to a regression. Re-opening.
