### ISSUE TITLE
Spektate dashboard fails to load when PR no longer exists

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1356]
**Describe the bug:**
The Spektate page will fail to load (but Docker image will continue to run) when a pull request id is given that no longer exists. 

From looking at the code there is a method called [getPullRequest](https://github.com/microsoft/spektate/blob/9e6dd796401f00deba96e863440abb99db18df7c/packages/spektate/src/repository/IAzureDevOpsRepo.ts#L33) that throws an error.

It looks like this eventually bubbles up to [here](https://github.com/microsoft/spektate/blob/94495812e9d9f2b99ad887d9dc1c373bc2823ba3/src/client/Dashboard.tsx#L256) and somehow we don't display anything on the page.

Here is a log from the Docker image
```
Error: Request failed with status code 404
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  config: {
    url: 'https://dev.azure.com/epicstuff/bedrock/_apis/git/repositories/fabrikam-hld/pullrequests/2501?api-version=5.1',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      Authorization: 'Basic ' +
        'xxx=',
      'User-Agent': 'axios/0.19.2'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function],
      abort: [Function],
      aborted: [Function],
      error: [Function],
      timeout: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'dev.azure.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'dev.azure.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 11561,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    connection: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'dev.azure.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'dev.azure.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 11561,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET ' +
      '/epicstuff/bedrock/_apis/git/repositories/fabrikam-hld/pullrequests/2501?api-version=5.1 ' +
      'HTTP/1.1\r' +
      '\nAccept: application/json, text/plain, */*\r' +
      '\nAuthorization: Basic ' +
      'xxx=\r' +
      '\nUser-Agent: axios/0.19.2\r' +
      '\nHost: dev.azure.com\r' +
      '\nConnection: close\r' +
      '\n\r' +
      '\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object],
      _eventsCount: 1,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      maxCachedSessions: 100,
      _sessionCache: [Object]
    },
    socketPath: undefined,
    method: 'GET',
    path: '/epicstuff/bedrock/_apis/git/repositories/fabrikam-hld/pullrequests/2501?api-version=5.1',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      connection: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular],
      responseUrl: 'https://dev.azure.com/epicstuff/bedrock/_apis/git/repositories/fabrikam-hld/pullrequests/2501?api-version=5.1',
      redirects: []
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function],
      _currentRequest: [Circular],
      _currentUrl: 'https://dev.azure.com/epicstuff/bedrock/_apis/git/repositories/fabrikam-hld/pullrequests/2501?api-version=5.1'
    },
    [Symbol(isCorked)]: false,
    [Symbol(outHeadersKey)]: [Object: null prototype] {
      accept: [Array],
      authorization: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 404,
    statusText: 'Not Found',
    headers: {
      'cache-control': 'no-cache, no-store, must-revalidate',
      pragma: 'no-cache',
      'content-length': '288',
      'content-type': 'application/json; charset=utf-8',
      expires: '-1',
      p3p: 'CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR ' +
        'SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"',
      'set-cookie': [Array],
      'x-tfs-processid': 'a5f63115-1f39-4c9f-b711-cf36ef4281dc',
      'strict-transport-security': 'max-age=31536000; includeSubDomains',
      activityid: 'bd3c1fdf-9ef7-4e11-adf9-f9e7774e8c7a',
      'x-tfs-session': 'bd3c1fdf-9ef7-4e11-adf9-f9e7774e8c7a',
      'x-vss-e2eid': 'bd3c1fdf-9ef7-4e11-adf9-f9e7774e8c7a',
      'x-vss-userdata': '2b289f68-3aec-410a-8404-b7eaf6c92137:abrig@microsoft.com',
      'x-frame-options': 'SAMEORIGIN',
      'request-context': 'appId=cid-v1:f88d1338-e7ba-4d7b-83e0-e573c40a2f62',
      'access-control-expose-headers': 'Request-Context',
      'x-content-type-options': 'nosniff',
      'x-msedge-ref': 'Ref A: 3B82523D68834B4A80743382D23CA6F0 Ref ' +
        'B: ASHEDGE0908 Ref C: 2020-04-16T00:16:06Z',
      date: 'Thu, 16 Apr 2020 00:16:06 GMT',
      connection: 'close'
    },
    config: {
      url: 'https://dev.azure.com/epicstuff/bedrock/_apis/git/repositories/fabrikam-hld/pullrequests/2501?api-version=5.1',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: ClientRequest {
      _events: [Object],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET ' +
        '/epicstuff/bedrock/_apis/git/repositories/fabrikam-hld/pullrequests/2501?api-version=5.1 ' +
        'HTTP/1.1\r' +
        '\nAccept: application/json, text/plain, */*\r' +
        '\nAuthorization: Basic ' +
        'XXX=\r' +
        '\nUser-Agent: axios/0.19.2\r' +
        '\nHost: dev.azure.com\r' +
        '\nConnection: close\r' +
        '\n\r' +
        '\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      path: '/epicstuff/bedrock/_apis/git/repositories/fabrikam-hld/pullrequests/2501?api-version=5.1',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      _redirectable: [Writable],
      [Symbol(isCorked)]: false,
      [Symbol(outHeadersKey)]: [Object]
    },
    data: {
      '$id': '1',
      innerException: null,
      message: 'TF401180: The requested pull request was not found.',
      typeName: 'Microsoft.TeamFoundation.Git.Server.GitPullRequestNotFoundException, ' +
        'Microsoft.TeamFoundation.Git.Server',
      typeKey: 'GitPullRequestNotFoundException',
      errorCode: 0,
      eventId: 3000
    }
  },
  isAxiosError: true,
  toJSON: [Function]
}
```
**To Reproduce:**
I will try loading a page that works. Deleting a reference to PR and refreshing.
 
**Expected behavior:**
We should gracefully handle this. We should give an indication that a particular piece of data couldn't be loaded

**Screenshots:**
<img width="759" alt="image" src="https://user-images.githubusercontent.com/3119513/79401353-b125d280-7f3d-11ea-92f6-ad47d4935715.png">
I looked at the code coverage and we don't have coverage on the area that is failing.

**Additional context:**

**Does this require updates to documentation?:**

**Comment by andrebriggs** [comment]
I was able to spin up a new process listening on Port 80 instead of 5000 and the dashboard loaded. This is on the running same container (meaning we are listening on port 5000 and port 80. Port 5000 doesn't work). Closing for now as there is probably some other issue we can't see
